apiVersion: apps/v1beta2
kind: Service
apiVersion: v1
metadata:
  name: drupal
spec:
  type: LoadBalancer
  selector:
    app: drupal
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80